# Generated by Django 5.2.1 on 2025-05-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('subHeading', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
    ]
