# Generated by Django 5.2.1 on 2025-05-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
